{{- if not .Values.networkPolicies }}
  {{- fail "A Network Policy must be defined under 'networkPolicies'." }}
{{- end }}

{{- range .Values.networkPolicies }}
  {{- if not .ingress }}
    {{- fail "The 'ingress' section is mandatory and must be specified for each Network Policy." }}
  {{- end }}

  {{- if not .egress }}
    {{- fail "The 'egress' section is mandatory and must be specified for each Network Policy." }}
  {{- end }}

apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: {{ .name }}
  {{- if .namespace }}
  namespace: {{ .namespace }}
  {{- end }}
spec:
  endpointSelector:
    matchLabels:
      {{- range $key, $value := .endpointSelector.matchLabels }}
      {{ $key }}: {{ $value }}
      {{- end }}
  ingress:
    {{- include "cilium.ingress" . | indent 4 }}
  egress:
    {{- include "cilium.egress" . | indent 4 }}
---
{{- end }}
